In [1]:
arr = [1,2,3,4]
print(arr)
type(arr)

[1, 2, 3, 4]


list

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)
type(arr1)

[1 2 3 4]


numpy.ndarray

In [6]:
arr1.shape # for 1D it shows the number of elements


(4,)

In [4]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [10]:
 array = np.arange(1,20,2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
array = np.arange(24).reshape(8,3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
array = np.arange(200,230,4)
array

array([200, 204, 208, 212, 216, 220, 224, 228])

In [20]:
array = np.arange(24).reshape(3,8)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [22]:
array = np.arange(24).reshape(1,24)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
array = np.arange(21).reshape(21,1)
array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [24]:
array = np.arange(24).reshape(12,2)
array


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [25]:
array = np.arange(24).reshape(2,12)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [26]:
array = np.arange(24).reshape(6,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])